### ISSUE TITLE
switch to muon tracker

### ISSUE THREAD

**Issue by wael444** [ehawkvu/kiss-xorg#87]
- [ ] atk [#92](https://github.com/ehawkvu/kiss-xorg/issues/92)
- [ ] atkmm [#92](https://github.com/ehawkvu/kiss-xorg/issues/92)
- [X] babl [#93](https://github.com/ehawkvu/kiss-xorg/issues/93) 
- [ ] cairomm [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
  + fails without libsigc++ 3.0 update
- [X] gcr [#90](https://github.com/ehawkvu/kiss-xorg/issues/90)
- [ ] gegl [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] gexiv2 [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] glibmm [#92](https://github.com/ehawkvu/kiss-xorg/issues/92) [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] gobject-introspection [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] gst-plugins-base [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] gstreamer [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] gtkmm3 [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] hexchat [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [x] i3
- [ ] libsecret [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [x] libsigc++ [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [x] libslirp
- [ ] pangomm [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [x] spice-protocol
- [ ] srain [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] xwayland
- [X] appstream-glib [#91](https://github.com/ehawkvu/kiss-xorg/issues/91) [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [ ] glib-networking [#91](https://github.com/ehawkvu/kiss-xorg/issues/91) 
- [ ] gimp [#93](https://github.com/ehawkvu/kiss-xorg/issues/93)
- [X] libsoup
- [ ] libsoup3
---
- [ ] freetype-harfbuzz (muon problem, unknown pkgconfig error)
  + harfbuzz-icu
- [ ] mesa (muon problem, can only be compiled with muon without LLVM, which requires disabling graphics methods that can break user experience)
- [ ] pango (muon problem, linking error)

**Comment by hovercats** [comment]
`gcr` can be skipped and dropped entierly, if we add the patch to surf.
if its of any interest? @ehawkvu

**Comment by wael444** [comment]
i thought community packages were supposed to be switched to muon by their maintainer, i guess i can have a shot at it.

**Comment by hovercats** [comment]
@wael444, if im not wrong, on kiss-xorg, its not as strict as on kiss-community/community..
so if people wanna submit prs, theyre free to do so. but by all means correct me if im wrong here.

@ehawkvu Ill make a PR for it.

**Comment by wael444** [comment]
@ehawkvu do you still use `hexchat` and `sylpheed`? both are maintained by you but need `gtk+2`.

**Comment by ehawkvu** [comment]
@wael444 I have them here because I don't see why having gtk+2 stuff around is a bad thing. That's why it's in community.

**Comment by wael444** [comment]
https://github.com/alpinelinux/aports/commit/f4fccd26eaa896b944f056ab71c6f55412198c16
> uses gtk-2.0

though, sylpheed is still kept in the repostories.

if i had a choice, i would rather remove all 3 of them for something better.

**Comment by wael444** [comment]
#97
